config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :photos, only: [:index, :show, :new, :create]

  get '/authorize_tweet' => 'photos#authorize_tweet'
  get '/oauth/callback' => 'photos#callback'
  post 'send_tweet' => 'photos#send_tweet'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :title, :image, presence: true
  validates :title, length: { maximum: 30 }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :photos

  validates :user_id, uniqueness: true
  validates :password_digest, :user_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :require_login

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  private

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to login_path
    end
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :require_login, only: [:home]
  def home
  end
end

app/controllers/photos_controller.rb
require 'uri'
require 'net/http'
require 'openssl'

class PhotosController < ApplicationController
  def index
    @photos = Photo.where(user: current_user).order(created_at: :desc)
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user = current_user

    if @photo.save
      redirect_to photos_path
    else
      render :new
    end
  end

  def authorize_tweet
    client_id = ENV['CLIENT_ID']
    redirect_uri = "http://localhost:3000/oauth/callback"
    redirect_to "https://arcane-ravine-29792.herokuapp.com/oauth/authorize?response_type=code&client_id=#{client_id}&redirect_uri=#{redirect_uri}"
  end

  def callback
    session[:code] = params[:code]
    request_access_token

    redirect_to photos_path
  end

  def send_tweet
    create_tweet
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :image)
  end

  def request_access_token
    @code = session[:code]

    client_id = ENV['CLIENT_ID']
    redirect_uri = "http://localhost:3000/oauth/callback"
    key = "Bearer #{ENV['CLIENT_SECRET']}"

    url = URI("https://arcane-ravine-29792.herokuapp.com/oauth/token?grant_type=authorization_code&code=#{@code}&client_id=#{client_id}&redirect_uri=#{redirect_uri}")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true

    request = Net::HTTP::Post.new(url)
    request["Accept"] = 'application/json'
    request["Content-Type"] = 'application/json'
    request["Authorization"] = key
    request.body = "{\"text\":\"\",\"url\":\"http://localhost:3000/photos/#{params[:photo]}.jpg\"}"
    response = http.request(request)
    body = JSON.parse(response.read_body)

    session[:access_token] = body['access_token']
  end

  def create_tweet
    key = "Bearer #{session[:access_token]}"
    url = URI("https://arcane-ravine-29792.herokuapp.com/api/tweets")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true

    request = Net::HTTP::Post.new(url)
    request["Accept"] = 'application/json'
    request["Content-Type"] = 'application/json'
    request["Authorization"] = key
    request.body = "{\"text\":\"テスト画像\",\"url\":\"http://localhost:3000/photos/#{params[:photo]}\"}"

    response = http.request(request)
    body = JSON.parse(response.read_body)
  
    if response.is_a?(Net::HTTPCreated)
      flash[:notice] = "ツイートを作成しました。"
      redirect_to photos_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    @user = User.find_by(user_id: params[:user_id])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to photos_path
    else
      if params[:user_id].empty? && params[:password].empty?
        flash[:alert] = "・ユーザーIDを入力してください"
        flash[:alert] << "<br>・パスワードを入力してください"
      elsif params[:user_id].empty?
        flash[:alert] = "・ユーザーIDを入力してください"
      elsif params[:password].empty?
        flash[:alert] = "・パスワードを入力してください"
      else
        flash[:alert] = "ユーザー名とパスワードが一致しません"
      end

      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    session[:code] = nil
    session[:access_token] = nil

    flash[:notice]="Logged Out"
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to photos_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_id, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1> Hello and Welcome <h1> 
<% if current_user %>
  <%= link_to 'Logout', logout_path %>
<% else %>
  <%= link_to 'Signup', signup_path%>
  <%= link_to 'Login', login_path%>
<% end %>

app/views/photos/index.html.erb
<%= link_to 'ログアウト', logout_path %>
<h1>写真一蘭</h1>
<%= link_to 'MyTweetappと連携', authorize_tweet_path %>
<br>
<%= link_to '写真アップロード', new_photo_path %>
<br>
<%= notice %>
<br>
<div class="photos">
  <% @photos.each do |photo| %>
    <div class="photo-card">
      <h4 class="title"><%= photo.title%></h4>
      <div class="image">
        <%= image_tag photo.image %>
      </div>
      <% if session[:code] %>
        <%= form_tag send_tweet_path(token: params[:code], photo: photo), method: :post do %>
          <%= submit_tag "ツイートする" %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/photos/new.html.erb
<%= link_to 'ログアウト', logout_path %>

<%= form_for @photo, url: photos_path do |form| %>
  <h1>写真アップロード</h1>
  <% if @photo.errors.full_messages.any? %>
    <% @photo.errors.full_messages.each do |error_message| %>
      <li class="error-message"><%= error_message %></li>
    <% end %>
  <% end %>
  <br>
  <%= form.label 'タイトル' %>
  <%= form.text_field :title %>
  <br>
  <%= form.label '画像ファイル' %>
  <%= form.file_field :image %>
  <br>
  <br>
  <%=  submit_tag("アップロード") %>
<% end %>
<%= link_to 'キャンセル', photos_path %>

app/views/photos/show.html.erb
<div>
  <%= @photo.title %>
  <%= image_tag @photo.image, width: 300 %>
</div>

app/views/users/new.html.erb
<%= link_to 'ホーム', root_path %>

<%= form_for @user, url: users_path do |form| %>
  <h2> アカウント登録 </h2>
    
  <%= form.label 'ユーザーID' %>
  <%= form.text_field :user_id, required: true %>
  <br>
  <%= form.label 'パスワード' %>
  <%= form.password_field :password, required: true %>
  <br>
  <br>
  <%=  submit_tag("アカウント登録") %>
<% end %>